### ISSUE TITLE
Ripping Skyfall

### ISSUE THREAD

**Issue by Jarrrk** [XDGimi/vrp_youtuber#1]
I am the creator of the Skyfall resource and you've just blatantly pasted my work into your script, I'd recommend any lines relating to Skyfall be removed and use the intended method of making Skyfall a resource dependency.

> Do not copy the resource without my permission

You can't say that when you've copied my resource without my permission.

**Comment by Jarrrk** [comment]
https://github.com/XDGimi/vRP-FiveM/blob/40effda29ba9f6473f291a34f70fae03ed49b510/vrp_premium/client.lua#L68-L119

**Comment by JimmyX99** [comment]
Ok, I deleted it
